In [2]:
#Ejercicio 1:  Importar numpy como np y imprimir la versión
#Respuesta:
import numpy as np
print(np.__version__)

1.18.1


In [3]:
#Ejercicio 2: ¿Cómo crear un arreglo 1D? 
#Crear un arreglo de 0 a 0

#Respuesta:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#Ejercicio 3: ¿Cómo crear un arreglo booleano?
# Crear un arreglo 3x3 llenado de True

#Respuesta:
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [5]:
#Ejercicio 4: ¿Cómo extraer los items que satisface cierta condición de un arreglo 1D?
#Extraer todos los impares de arr
arr = np.arange(10)

#Respuesta:
arr[arr%2==1]

array([1, 3, 5, 7, 9])

In [6]:
#Ejercicio 5: ¿Cómo reemplazar items que satisface una condición con otro valor en el arreglo?
#Reemplazar todos los impares por -1
arr = np.arange(10)

#Respuesta:
arr[arr%2==1]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [7]:
#Ejercicio 6: ¿Cómo reemplazr items que satisface una condición sin afectar el arreglo original?
#Reemplaze todos los impares por -1 sin afectar el arreglo arr
arr = np.arange(10)

#Respuesta:
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [8]:
#Ejercicio 7: ¿Cómo remodelar un arreglo?
#Convierta un arreglo 1D en un arreglo 2D con 2 filas
arr = np.arange(10)

#Respuesta:
arr.reshape(2, -1)  #Enviando -1: numpy automaticamente decide el numero de columnas

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
#Ejercicio 8: ¿Cómo apilar 2 arreglos verticalmente?
#Apile el arreglo a y b verticalmente
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1) 

# Respuestas
# Metódo 1:
np.concatenate([a, b], axis=0)

# Metódo 2:
np.vstack([a, b])

# Metódo 3:
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
#Ejercicio 9: ¿Cómo apliar 2 arreglos horizontalmente?
#Apile el arreglo a y b horizontalmente
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Respuestas
# Metodo 1:
np.concatenate([a, b], axis=1)

# Metodo 2:
np.hstack([a, b])

# Metodo 3:
np.c_[a, b] 

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [11]:
#Ejercicio 10: ¿Cómo generar secuencias personalizadas en numpy sin hardcoding?
#Cree el siguiente patrón sin hardcoding. Utilice solo funciones numpy y la siguien te matriz de entrada a
a = np.array([1,2,3])

#Respuesta:
np.r_[np.repeat(a, 3), np.tile(a, 3)]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [12]:
#Ejercicio 11: ¿Cómo obtener los items comunes de dos arreglos numpy?
#Obtener los items comunes de a y b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

#Respuesta:
np.intersect1d(a,b)

array([2, 4])

In [13]:
#Ejercicio 12: ¿Cómo eliminar los items de una arreglo que no existen en otro?
#Del arreglo 'a' eliminar todos los elementos presentes en la matriz 'b'
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

#Respuesta:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [14]:
#Ejercicio 13: ¿Cómo obtener las posiciones donde coinciden los elementos de dos matrices?
#Obtenga las posiciones donde los elementos de 'a' y 'b' coinciden
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

#Respueta:
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

In [15]:
#Ejercicio 14: ¿Cómo extraer todos los números entre un rango dado de un arreglo numpy?
#Obtenga todos los artículos entre 5 y 10 de 'a'.
a = np.arange(15)

#Respuestas
# Metódo 1
index = np.where((a >= 5) & (a <= 10))
a[index]

# Metódo 2:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]

# Metódo 3:  
a[(a >= 5) & (a <= 10)]

array([ 5,  6,  7,  8,  9, 10])

In [16]:
#Ejercicio 15: ¿Cómo hacer una función de python que maneje escalares para trabajar en arreglos numpy?
#Convierta la función 'maxx' que funciona en dos escalares, para trabajar en dos matrices.
def maxx(x, y):
    """Obtiene el máximo de dos items"""
    if x >= y:
        return x
    else:
        return y
    
#Respuesta:
pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

In [17]:
#Ejercicio 16: ¿Cómo intercambiar dos columnas en un arreglo numpy 2d?
#Intercambie las columnas 1 y 2 en la matriz arr

arr = np.arange(9).reshape(3,3) 

#Respuesta:
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [18]:
#Ejercicio 17: ¿Cómo intercambiar dos filas en un arreglo numpy 2d?
#Intercambie las filas 1 y 2 en la matriz arr
arr = np.arange(9).reshape(3,3)

#Respuesta:
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [19]:
#Ejercicio 18: ¿Cómo invertir las filas de una arreglo 2D?
#Invierta las filas de una arreglo 2D 'arr'.
arr = np.arange(9).reshape(3,3)

#Respuesta:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [20]:
#Ejercicio 19: ¿Cómo invertir las columnas de una arreglo 2D?
#Invierta las columnas de una arreglo 2D 'arr'.
arr = np.arange(9).reshape(3,3)

#Respuesta:
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [21]:
#Ejercicio 20: ¿Cómo crear una matriz 2D que contenga flotantes aleatorios entre 5 y 10?
#Cree una matriz 2D de forma 5x3 para contener números decimales aleatorios entre 5 y 10

arr = np.arange(9).reshape(3,3)

#Respuestas
# Método 1:
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
#print(rand_arr)

# Método 2:
rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)

[[6.97531433 9.99892715 8.51241244]
 [7.99623553 7.25079691 8.67213163]
 [8.64506284 7.73534444 6.34207319]
 [8.88833357 9.68111453 8.29246606]
 [7.90292286 6.11872355 5.2108744 ]]


In [22]:
#Ejercicio 21: ¿Cómo imprimir solo 3 lugares decimales en la matriz numpy de python?
#Imprime o muestra solo 3 decimales de la matriz numpy 'rand_arr'
rand_arr = np.random.random((5,3))

#Respuesta:
np.set_printoptions(precision=3)
rand_arr[:4]

array([[0.782, 0.125, 0.56 ],
       [0.047, 0.685, 0.355],
       [0.779, 0.397, 0.554],
       [0.038, 0.476, 0.34 ]])

In [23]:
#Ejercicio 22: ¿Cómo imprimir bonito una matriz numpy suprimiendo la notación científica (como 1e10)?
#Imprime rand_arr de forma bonita suprimiendo la notación científica (como 1e10)

#Resetiar del ejercicio anterior
np.set_printoptions(suppress=False)

# Creando una matriz randon
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

#Respuesta:
np.set_printoptions(suppress=True, precision=6)  # precision is optional
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

In [24]:
#Ejercicio 23: ¿Cómo limitar el número de elementos impresos en la salida de una matriz numpy?
#Limite el número de elementos impresos en python numpy array a a un máximo de 6 elementos.

a = np.arange(15)

#Respuesta:
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [25]:
#Ejercicio 24: ¿Cómo imprimir la matriz numpy completa sin truncar?
#Imprima la matriz numpy completa a sin truncar.
np.set_printoptions(threshold=6)
a = np.arange(15)

#Respuesta:
np.set_printoptions(threshold=1000) #1000 es por defecto threshol 
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
#Ejercicio 25 ¿Cómo importar un conjunto de datos con números y textos manteniendo el texto intacto en Python numpy?

#Explicación: Se desea obtener un dataset para eso se hace uso del metodo genfromtxt del modulo numpy.

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
print(iris[:3])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']]


In [55]:
#Ejercicio 26 ¿Cómo extraer una columna particular de una matriz de tuplas 1D?

#Explicación: Se hace uso del metodo anterior y luego se realiza la conversión usando el metodo .array del modulo numpy.

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

species = np.array([row[4] for row in iris_1d])
species[:3]

C:\Users\Usuario\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa'], dtype='|S18')

In [32]:
#Ejercicio 27 ¿Cómo convertir una matriz 1d de tuplas a una matriz numpy 2d?

#Explicación: Se hace uso de las funciones de los ejercicios 25 y 26. Se convierte cada fila en una lista y se obtienen
#los primeros 4 elementos

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',')

iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
iris_2d[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [35]:
#Ejercicio 28 ¿Cómo calcular la media, mediana, desviación estándar de una matriz numpy?

#Explicación: Para calcular la media, mediana y desviación estándar se hace uso del metodo del ejercicio 25 y posteriormente
#se hace uso de los metodos .mean , .median y .std del modulo Numpy. 

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

mu, med, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print(mu, med, sd)

5.843333333333334 5.8 0.8253012917851409


In [36]:
#Ejercicio 29 ¿Cómo normalizar una matriz para que los valores oscilen exactamente entre 0 y 1?

#Explicación: Se obtienen el maximo y minimo valor de la matriz y posteriormente se realiza el preocedimiento con la 
#formula S

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

Smax, Smin = sepallength.max(), sepallength.min()
S = (sepallength - Smin)/(Smax - Smin)
print(S)

[0.222222 0.166667 0.111111 0.083333 0.194444 0.305556 0.083333 0.194444
 0.027778 0.166667 0.305556 0.138889 0.138889 0.       0.416667 0.388889
 0.305556 0.222222 0.388889 0.222222 0.305556 0.222222 0.083333 0.222222
 0.138889 0.194444 0.194444 0.25     0.25     0.111111 0.138889 0.305556
 0.25     0.333333 0.166667 0.194444 0.333333 0.166667 0.027778 0.222222
 0.194444 0.055556 0.027778 0.194444 0.222222 0.138889 0.222222 0.083333
 0.277778 0.194444 0.75     0.583333 0.722222 0.333333 0.611111 0.388889
 0.555556 0.166667 0.638889 0.25     0.194444 0.444444 0.472222 0.5
 0.361111 0.666667 0.361111 0.416667 0.527778 0.361111 0.444444 0.5
 0.555556 0.5      0.583333 0.638889 0.694444 0.666667 0.472222 0.388889
 0.333333 0.333333 0.416667 0.472222 0.305556 0.472222 0.666667 0.555556
 0.361111 0.333333 0.333333 0.5      0.416667 0.194444 0.361111 0.388889
 0.388889 0.527778 0.222222 0.388889 0.555556 0.416667 0.777778 0.555556
 0.611111 0.916667 0.166667 0.833333 0.666667 0.805556 0.6111

In [38]:
#Ejercicio 30 ¿Cómo calcular la puntuación softmax?

#Explicación: Se crea una función que permite encontrar el valor maximos del conjunto de datos. 

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

print(softmax(sepallength))

[0.00222  0.001817 0.001488 0.001346 0.002008 0.002996 0.001346 0.002008
 0.001102 0.001817 0.002996 0.001644 0.001644 0.000997 0.00447  0.004044
 0.002996 0.00222  0.004044 0.00222  0.002996 0.00222  0.001346 0.00222
 0.001644 0.002008 0.002008 0.002453 0.002453 0.001488 0.001644 0.002996
 0.002453 0.003311 0.001817 0.002008 0.003311 0.001817 0.001102 0.00222
 0.002008 0.001218 0.001102 0.002008 0.00222  0.001644 0.00222  0.001346
 0.002711 0.002008 0.01484  0.008144 0.013428 0.003311 0.009001 0.004044
 0.007369 0.001817 0.009947 0.002453 0.002008 0.00494  0.005459 0.006033
 0.003659 0.010994 0.003659 0.00447  0.006668 0.003659 0.00494  0.006033
 0.007369 0.006033 0.008144 0.009947 0.01215  0.010994 0.005459 0.004044
 0.003311 0.003311 0.00447  0.005459 0.002996 0.005459 0.010994 0.007369
 0.003659 0.003311 0.003311 0.006033 0.00447  0.002008 0.003659 0.004044
 0.004044 0.006668 0.00222  0.004044 0.007369 0.00447  0.016401 0.007369
 0.009001 0.02704  0.001817 0.020032 0.010994 0.01812

In [39]:
#Ejercicio 31 ¿Cómo encontrar los puntajes percentiles de una matriz numpy?

#Explicación: Despues de extraer el dataset se hace uso del metodo percentile del modulo numpy

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

np.percentile(sepallength, q=[5, 95])

array([4.6  , 7.255])

In [12]:
#Ejercicio 32 ¿Cómo insertar valores en posiciones aleatorias en una matriz?

#Explicación: Despues de cargar el dataset se hace uso del metodo random para definir el rango de numeros aleatorios
#que sea desea poner dentro de la matriz. Al final se puede comparar el antes y despues de como queda estructurada. 

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
np.random.seed(100)
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
print(iris_2d[:,3])

[b'0.2' b'0.2' b'0.2' b'0.2' b'0.2' b'0.4' b'0.3' b'0.2' b'0.2' b'0.1'
 b'0.2' b'0.2' b'0.1' b'0.1' b'0.2' b'0.4' b'0.4' b'0.3' b'0.3' b'0.3'
 b'0.2' b'0.4' b'0.2' b'0.5' nan b'0.2' b'0.4' b'0.2' b'0.2' b'0.2' b'0.2'
 b'0.4' b'0.1' b'0.2' b'0.1' b'0.2' b'0.2' b'0.1' b'0.2' b'0.2' b'0.3'
 b'0.3' b'0.2' b'0.6' b'0.4' b'0.3' b'0.2' b'0.2' b'0.2' b'0.2' b'1.4'
 b'1.5' b'1.5' b'1.3' b'1.5' b'1.3' b'1.6' b'1.0' b'1.3' b'1.4' nan b'1.5'
 b'1.0' b'1.4' b'1.3' b'1.4' nan b'1.0' b'1.5' b'1.1' b'1.8' b'1.3' b'1.5'
 b'1.2' b'1.3' b'1.4' b'1.4' b'1.7' b'1.5' b'1.0' b'1.1' b'1.0' b'1.2'
 b'1.6' b'1.5' b'1.6' b'1.5' b'1.3' b'1.3' b'1.3' b'1.2' b'1.4' b'1.2'
 b'1.0' b'1.3' b'1.2' b'1.3' b'1.3' b'1.1' b'1.3' b'2.5' b'1.9' b'2.1' nan
 b'2.2' b'2.1' b'1.7' nan b'1.8' b'2.5' b'2.0' b'1.9' b'2.1' b'2.0' b'2.4'
 b'2.3' b'1.8' b'2.2' b'2.3' b'1.5' b'2.3' b'2.0' b'2.0' b'1.8' b'2.1'
 b'1.8' b'1.8' b'1.8' b'2.1' b'1.6' b'1.9' b'2.0' b'2.2' b'1.5' b'1.4'
 b'2.3' b'2.4' b'1.8' nan b'2.1' b'2.4' b'2.3' b'1.9' nan

In [45]:
#Ejercicio 33 ¿Cómo encontrar la posición de los valores faltantes en una matriz numpy?

#Explicación: Se carga el dataset, posteriormente se hace uso del metodo del ejercicio anterior donde se rellena con valores
#faltantes, tambien se utiliza isnan para contar la cantitdad de numeros que hacen faltan y np.where para obtener las
#posiciones de estos espacios en blanco. 

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

print("Number of missing values: \n", np.isnan(iris_2d[:, 0]).sum())
print("Position of missing values: \n", np.where(np.isnan(iris_2d[:, 0])))

Number of missing values: 
 5
Position of missing values: 
 (array([ 38,  80, 106, 113, 121], dtype=int64),)


In [34]:
#Ejercicio 34 ¿Cómo filtrar una matriz numpy basada en dos o más condiciones?

#Explicación: Despues de haber cargado el dataset se puede establecer en una variable la condicion. Luego esa condición se usa
#para obtener los valores correspondientes. 

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
condition = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
iris_2d[condition]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [49]:
#Ejercicio 35 ¿Cómo filtrar filas que contienen un valor faltante de una matriz numpy?

#Explicación: Para filtrar columnas que tienen un valor faltante se hace uso del metodo isnan. 

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
iris_2d[np.sum(np.isnan(iris_2d), axis = 1) == 0][:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4]])

In [50]:
#Ejercicio 36 ¿Cómo encontrar la correlación entre dos columnas de una matriz numpy?

#Explicación: Despues de cargar el data set se hace uso del metodo corrcoef en el que es necesario especificar las columnas de 
#la matriz en las que se desea encontra la correlación 

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

np.corrcoef(iris[:, 0], iris[:, 2])[0, 1]

0.8717541573048718

In [37]:
#Ejercicio 37 ¿Cómo encontrar si una matriz dada tiene algún valor nulo?

#Explicación: Haciendo uso del metodo isnan y el metodo any se obtiene si la matriz tiene un valor nulo o no. 

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
np.isnan(iris_2d).any()

False

In [38]:
#Ejercicio 38 ¿Cómo reemplazar todos los valores faltantes con 0 en una matriz numpy?

#Explicación: Como si fuera una condición se puede hacer uso de otro metodo como isnan para remplazar los valores faltantes con 0

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
iris_2d[np.isnan(iris_2d)] = 0
iris_2d[:4]

array([[5.1, 3.5, 1.4, 0. ],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [39]:
#Ejercicio 39 ¿Cómo encontrar el recuento de valores únicos en una matriz numpy?
 
#Explicación: Haciendo uso del metodo unique del modulo numpy se puede obtener los valores unicos. 

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
species = np.array([row.tolist()[4] for row in iris])
np.unique(species, return_counts=True)

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype='|S15'),
 array([50, 50, 50], dtype=int64))

In [40]:
#Ejercicio 40 ¿Cómo convertir una matriz numérica en una matriz categórica (texto)?

#Explicación: Haciendo uso del metodo .digitize se obtiene los indices de los labels de la matriz. Luego se realiza un mapeo
#haciendo uso de una colección y finalmente se recorre la matriz para realizar dicha conversión. 

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
petal_length_bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5, 10])
label_map = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}
petal_length_cat = [label_map[x] for x in petal_length_bin]
petal_length_cat[:4]

['small', 'small', 'small', 'small']

In [41]:
#Ejercicio 41 ¿Cómo crear una nueva columna a partir de columnas existentes de una matriz numpy?

#Explicación: Para crear una columna nueva se debe partir la matriz adicionar la columna y posteriormente volver a unir con el
#metodo .hstack

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = iris_2d[:, 0].astype('float')
petallength = iris_2d[:, 2].astype('float')
volume = (np.pi * petallength * (sepallength**2))/3
volume = volume[:, np.newaxis]
out = np.hstack([iris_2d, volume])
out[:4]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa',
        38.13265162927291],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa',
        35.200498485922445],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa', 30.0723720777127],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa',
        33.238050274980004]], dtype=object)

In [51]:
#Ejercicio 42 ¿Cómo hacer un muestreo probabilístico en numpy?

#Explicación: Si se desea ralizar un muestreo probabilistico basta con hacer uso del metodo random,choice y especificar los labels
#donde se desea realizar el análisis. 

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

species = iris[:, 4]
np.random.seed(100)
a = np.array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])
species_out = np.random.choice(a, 150, p=[0.5, 0.25, 0.25])
print(np.unique(species_out, return_counts=True))

(array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype='<U15'), array([77, 37, 36], dtype=int64))


In [43]:
#Ejercicio 43 ¿Cómo obtener el segundo valor más grande de una matriz cuando se agrupa por otra matriz?

#Explicación: Para obtener el segundo valor más grande de una matriz se hace uso del metodo sort y del metodo unique. 

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

petal_len_setosa = iris[iris[:, 4] == b'Iris-setosa', [2]].astype('float')
np.unique(np.sort(petal_len_setosa))[-2]

1.7

In [52]:
#Ejercicio 44 Cómo ordenar una matriz 2D por una columna

#Explicación: Primero es necesario elegir la columna donde se desea realizar el ordenamiento, luego se hace uso del 
#metodo argsort() que devuelve el arreglo ordenado y se evalua para obtener la matriz deseada. 

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
condition=iris[:,0].argsort()
print(iris[condition][:5])  

[[b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'4.4' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'3.0' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.5' b'2.3' b'1.3' b'0.3' b'Iris-setosa']]


In [45]:
#Ejercicio 45 ¿Cómo encontrar el valor más frecuente en una matriz numpy?

#Explicación: Primero se selecciona o delimita la columa donde se desea encontrar el valor más frecuente, luego se hace uso del
#metodo unique que retorna los valores y la cantidad de veces que se repiten. Finalmente se encuentra el valor maximo con el
#metodo argmax y se extrae de la matriz. 

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

vals, counts = np.unique(iris[:, 2], return_counts=True)
print(vals,len(vals))
print(counts,len(counts))
print(np.argmax(counts))
print(vals[np.argmax(counts)])

[b'1.0' b'1.1' b'1.2' b'1.3' b'1.4' b'1.5' b'1.6' b'1.7' b'1.9' b'3.0'
 b'3.3' b'3.5' b'3.6' b'3.7' b'3.8' b'3.9' b'4.0' b'4.1' b'4.2' b'4.3'
 b'4.4' b'4.5' b'4.6' b'4.7' b'4.8' b'4.9' b'5.0' b'5.1' b'5.2' b'5.3'
 b'5.4' b'5.5' b'5.6' b'5.7' b'5.8' b'5.9' b'6.0' b'6.1' b'6.3' b'6.4'
 b'6.6' b'6.7' b'6.9'] 43
[ 1  1  2  7 12 14  7  4  2  1  2  2  1  1  1  3  5  3  4  2  4  8  3  5
  4  5  4  8  2  2  2  3  6  3  3  2  2  3  1  1  1  2  1] 43
5
b'1.5'


In [46]:
#Ejercicio 46 ¿Cómo encontrar la posición de la primera aparición de un valor mayor que un valor dado?

#Explicación: Haciendo uso del metodo argwhere se encuentram los índices de los elementos de la matriz que no son cero
#y son agrupados por elemento.

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
np.argwhere(iris[:, 3].astype(float)>1.0)[0]

array([50], dtype=int64)

In [60]:
#Ejercicio 47  ¿Cómo reemplazar todos los valores mayores que un valor dado a un límite dado?

#Explicación: Haciendo uso del metodo clip dado un intervalo, los valores fuera del intervalo se
#recortan en los bordes del intervalo.

np.set_printoptions(precision=2)
np.random.seed(100)
a = np.random.uniform(1,50, 20)
print(a)
np.clip(a, a_min=10, a_max=30)

[27.63 14.64 21.8  42.39  1.23  6.96 33.87 41.47  7.7  29.18 44.67 11.25
 10.08  6.31 11.77 48.95 40.77  9.43 41.   14.43]


array([27.63, 14.64, 21.8 , 30.  , 10.  , 10.  , 30.  , 30.  , 10.  ,
       29.18, 30.  , 11.25, 10.08, 10.  , 11.77, 30.  , 30.  , 10.  ,
       30.  , 14.43])

In [61]:
#48) Get the positions of top 5 maximum values in a given array a.
np.random.seed(100)
a = np.random.uniform(1,50, 20)
#Respuesta
print(a.argsort())

[ 4 13  5  8 17 12 11 14 19  1  2  0  9  6 16 18  7  3 10 15]


In [62]:
#49) Compute the counts of unique values row-wise.
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr
#Respuesta
def counts_of_all_values_rowwise(arr2d):
    num_counts_array = [np.unique(row, return_counts=True) for row in arr2d]
    return([[int(b[a==i]) if i in a else 0 for i in np.unique(arr2d)] for a, b in num_counts_array])
print(np.arange(1,11))
counts_of_all_values_rowwise(arr)

[ 1  2  3  4  5  6  7  8  9 10]


[[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
 [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
 [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
 [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
 [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
 [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]

In [63]:
#50) Convert array_of_arrays into a flat linear 1d array.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)
#Respuesta
array_of_arrays = np.array([arr1, arr2, arr3])
array_of_arrays
arr_2d = np.array([a for arr in array_of_arrays for a in arr])
print(arr_2d)

[0 1 2 3 4 5 6 7 8 9]


In [64]:
#51) Compute the one-hot encodings (dummy binary variables for each unique value in the array)
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
#Respuesta
def one_hot_encodings(arr):
    uniqs = np.unique(arr)
    out = np.zeros((arr.shape[0], uniqs.shape[0]))
    for i, k in enumerate(arr):
        out[i, k-1] = 1
    return out
one_hot_encodings(arr)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [65]:
#52) Create row numbers grouped by a categorical variable. Use the following sample from iris species as input.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))
species_small
#Respuesta
print([i for val in np.unique(species_small) for i, grp in enumerate(species_small[species_small==val])])

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 6, 7, 8]


In [66]:
#53) Create group ids based on a given categorical variable. Use the following sample from iris species as input.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))
species_small 
#Respeusta
output = [np.argwhere(np.unique(species_small) == s).tolist()[0][0] for val in np.unique(species_small) for s in species_small[species_small==val]]
print(output)

[0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2]


In [67]:
#54) Create the ranks for the given numeric array a.
np.random.seed(10)
a = np.random.randint(20, size=10)
print(a)
print("--------------------")
#Respuesta
print(a.argsort().argsort())

[ 9  4 15  0 17 16 17  8  9  0]
--------------------
[4 2 6 0 8 7 9 3 5 1]


In [68]:
#55) Create a rank array of the same shape as a given numeric array a.
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)
print("---------------------------")
#Respuesta
print(a.ravel().argsort().argsort().reshape(a.shape))

[[ 9  4 15  0 17]
 [16 17  8  9  0]]
---------------------------
[[4 2 6 0 8]
 [7 9 3 5 1]]


In [69]:
#56) Compute the maximum for each row in the given array.
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
#Respuesta
np.amax(a, axis=1)

array([9, 8, 6, 3, 9])

In [70]:
#57)  Compute the min-by-max for each row for given 2d numpy array.
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
#Respuesta
np.apply_along_axis(lambda x: np.min(x)/np.max(x), arr=a, axis=1)

array([0.44, 0.12, 0.5 , 1.  , 0.11])

In [71]:
#58) Find the duplicate entries (2nd occurrence onwards) in the given numpy array 
#and mark them as True. First time occurrences should be False
np.random.seed(100)
a = np.random.randint(0, 5, 10)
#Respuesta
out = np.full(a.shape[0], True)
unique_positions = np.unique(a, return_index=True)[1]
out[unique_positions] = False
print(out)

[False  True False  True False False  True  True  True  True]


In [72]:
#59) Find the mean of a numeric column grouped by a categorical column in a 2D numpy array
#Respuesta
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
numeric_column = iris[:, 1].astype('float') 
grouping_column = iris[:, 4] 
[[group_val, numeric_column[grouping_column==group_val].mean()] for group_val in np.unique(grouping_column)]
output = []
for group_val in np.unique(grouping_column):
    output.append([group_val, numeric_column[grouping_column==group_val].mean()])
    
print(output)

[[b'Iris-setosa', 3.418], [b'Iris-versicolor', 2.7700000000000005], [b'Iris-virginica', 2.974]]


In [73]:
#60) Import the image from the following URL and convert it to a numpy array
#Respuesta
from io import BytesIO
from PIL import Image
import PIL, requests
URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'
response = requests.get(URL)
I = Image.open(BytesIO(response.content))
I = I.resize([150,150])
arr = np.asarray(I)
im = PIL.Image.fromarray(np.uint8(arr))
Image.Image.show(im)

In [74]:
#61) Drop all nan values from a 1D numpy array
np.array([1,2,3,np.nan,5,6,7,np.nan])
#Respuesta
a[~np.isnan(a)]

array([0, 0, 3, 0, 2, 4, 2, 2, 2, 2])

In [75]:
#62) Compute the euclidean distance between two arrays a and b.
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
#Respuesta
dist = np.linalg.norm(a-b)
dist

6.708203932499369

In [76]:
#63) Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
#Respuesta
doublediff = np.diff(np.sign(np.diff(a)))
peak_locations = np.where(doublediff == -2)[0] + 1
peak_locations

array([2, 5], dtype=int64)

In [77]:
#64) Subtract the 1d array b_1d from the 2d array a_2d, such that each item of b_1d subtracts from respective row of a_2d.
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,1,1])
#Respuesta
print(a_2d - b_1d[:,None])

[[2 2 2]
 [3 3 3]
 [4 4 4]]


In [78]:
#65) Find the index of 5th repetition of number 1 in x
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
#Respuesta
n = 5
[i for i, v in enumerate(x) if v == 1][n-1]
np.where(x == 1)[0][n-1]

8

In [79]:
#66) Convert numpy's datetime64 object to datetime's datetime object
dt64 = np.datetime64('2018-02-25 22:10:10')
#Respuesta
from datetime import datetime
dt64.tolist()
dt64.astype(datetime)

datetime.datetime(2018, 2, 25, 22, 10, 10)

In [80]:
#67) Compute the moving average of window size 3, for the given 1D array.
np.random.seed(100)
Z = np.random.randint(10, size=10)
#Respuesta
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
np.random.seed(100)
Z = np.random.randint(10, size=10)
print('array: ', Z)
moving_average(Z, n=3).round(2)
np.convolve(Z, np.ones(3)/3, mode='valid')  

array:  [8 8 3 7 7 0 4 2 5 2]


array([6.33, 6.  , 5.67, 4.67, 3.67, 2.  , 3.67, 3.  ])

In [81]:
#68) Create a numpy array of length 10, starting from 
#5 and has a step of 3 between consecutive numbers
#Respuesta
length = 10
start = 5
step = 3
def seq(start, length, step):
    end = start + (step*length)
    return np.arange(start, end, step)
seq(start, length, step)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

In [82]:
#69) Given an array of a non-continuous sequence of dates. Make it a continuous sequence of dates, 
#by filling in the missing dates.
dates = np.arange(np.datetime64('2018-02-01'), np.datetime64('2018-02-25'), 2)
print(dates)
#Respuesta
filled_in = np.array([np.arange(date, (date+d)) for date, d in zip(dates, np.diff(dates))]).reshape(-1)
output = np.hstack([filled_in, dates[-1]])
output
out = []
for date, d in zip(dates, np.diff(dates)):
    out.append(np.arange(date, (date+d)))
filled_in = np.array(out).reshape(-1)
output = np.hstack([filled_in, dates[-1]])


['2018-02-01' '2018-02-03' '2018-02-05' '2018-02-07' '2018-02-09'
 '2018-02-11' '2018-02-13' '2018-02-15' '2018-02-17' '2018-02-19'
 '2018-02-21' '2018-02-23']


In [83]:
#70) From the given 1d array arr, generate a 2d matrix using strides, 
#with a window length of 4 and strides of 2, like [[0,1,2,3], [2,3,4,5], [4,5,6,7]..]
arr = np.arange(15) 
arr

#Respuesta
def gen_strides(a, stride_len=5, window_len=5):
    n_strides = ((a.size-window_len)//stride_len) + 1
    # return np.array([a[s:(s+window_len)] for s in np.arange(0, a.size, stride_len)[:n_strides]])
    return np.array([a[s:(s+window_len)] for s in np.arange(0, n_strides*stride_len, stride_len)])

print(gen_strides(np.arange(15), stride_len=2, window_len=4))

[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]
