By: Jhoan Sebastian Saavedra Romero cc: 1010238118

In [46]:
#1:  Import the numpy package under the name `np`
#Respuesta:
import numpy as np

In [5]:
#2: Print the numpy version and the configuration
print(np.__version__)
np.__config__.show()

1.18.1
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


In [6]:
#3: Create a null vector of size 10
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
#4: How to find the memory size of any array
arr=np.zeros(10)

#Respuesta
print(arr.itemsize*arr.size)

80


#Ejercicio 5:  How to get the documentation of the numpy add function from the command line ?

Utilizamos los siguientes comandos
python -c "import numpy; numpy.info(numpy.add)"

In [14]:
#6: Create a null vector of size 10 but the fifth value which is 1
arr= np.zeros(10)
arr[4]= 1
print (arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [15]:
#Ejercicio 7: Create a vector with values ranging from 10 to 49
arr=np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [16]:
#8: Reverse a vector (first element becomes last)
arr = np.arange(1,10)
arr= arr[::-1]
print (arr)

[9 8 7 6 5 4 3 2 1]


In [17]:
#9 Create a 3x3 matrix with values ranging from 0 to 8
arr= np.arange(9).reshape(3,3)
print (arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [18]:
#10  Find indices of non-zero elements from [1,2,0,0,4,0]
arr= np.nonzero([1,2,0,0,4,0])
print(arr)

(array([0, 1, 4], dtype=int64),)


In [19]:
#11 Create a 3x3 identity matrix
arr= np.eye(3)
print (arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
#12 Create a 3x3x3 array with random values
arr = np.random.uniform((3,3,3))
print (arr)

[2.20043732 2.35718888 2.87872364]


In [21]:
#13 Create a 10x10 array with random values and find the minimum and maximum values
arr = np.random.random((10,10))
Arrmin=arr.min(), 
Arrmax=arr.max()
print(Arrmin, Arrmax)

(0.01102628344031531,) 0.9950810943889655


In [22]:
#Ejercicio 14 Create a random vector of size 30 and find the mean value
arr = np.random.random(10)
mean = arr.mean()
print (mean)

0.47423080436839066


In [24]:
#15 Create a 2d array with 1 on the border and 0 inside
arr = np.ones((10,10))
arr[1:-1,1:-1]=0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [32]:
#16 How to add a border (filled with 0's) around an existing array?
arr = np.ones((10,10)) 
x = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
#17 What is the result of the following expression?


In [33]:
#18 Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
arr= np.diag(1+np.arange(4), k = -1)
print (arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [4]:
#19 Create a 8x8 matrix and fill it with a checkerboard pattern
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [25]:
#20 Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [33]:
#21. Create a checkerboard 8x8 matrix using the tile function
#Z = np.tile( np.array([[0,1],[1,0],[2,4]]), (2,2))
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [35]:
#22. Normalize a 5x5 random matrix
A = np.random.random((5,5))
Amax, Amin = A.max(), A.min()
A = (A - Amin)/(Amax - Amin)
print(A)

[[0.18192311 0.55679817 0.85572578 0.96027605 0.94450974]
 [0.28423938 0.63407956 0.12559098 1.         0.4273374 ]
 [0.         0.78688782 0.10762704 0.88751694 0.20512384]
 [0.87304012 0.67806236 0.60460909 0.31106819 0.99155049]
 [0.84356441 0.99804163 0.98601922 0.17351243 0.99959575]]


In [38]:
#23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


C:\Users\ASUS\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


In [40]:
#24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
A = np.dot(np.ones((5,3),dtype=int), np.ones((3,2),dtype=int))
print(A)

[[3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]]


In [42]:
#25. Given a 1D array, negate all elements which are between 3 and 8, in place.
A = np.arange(11)
A[(A>3) & (A <= 8)] *= -1
print(A)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [48]:
#26. What is the output of the following script?
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
print("La verdad no sé")

10
10
La verdad no sé


In [52]:
#27. Consider an integer vector Z, which of these expressions are legal? (
Z=np.arange(10)
print(Z)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print("La expresión: Z<Z>Z no es legal")

[0 1 2 3 4 5 6 7 8 9]
[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[  0   1   2   4   8  16  32  64 128 256]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
La expresión: Z<Z>Z no es legal


In [53]:
#28. What are the result of the following expressions?
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\ASUS\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
C:\Users\ASUS\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [55]:
#29. How to round away from zero a float array ?
Z = np.random.uniform(-10,+10,10)
print(Z)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[-1.13844154e+00  2.79946489e-03  7.67191998e+00 -1.18388992e+00
 -8.98088760e+00  8.27096405e+00 -5.13255967e-01 -1.50364241e+00
 -2.00901099e+00 -1.68916712e+00]
[-2.  1.  8. -2. -9.  9. -1. -2. -3. -2.]


In [56]:
#### 30. How to find common values between two arrays?
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 1 3 6 7]


In [59]:
#### 31. How to ignore all numpy warnings (not recommended)?
defaults = np.seterr(all="ignore") #Ignora
Z = np.ones(1) / 0
_ = np.seterr(**defaults) #Vuelve a la normalidad

In [68]:
#### 32. Is the following expressions true?
a=np.sqrt(-1)
b=np.emath.sqrt(-1)
print("np.sqrt(-1)= {} y np.emath.sqrt(-1)={} No son iguales ya que el segundo maneja complejos y el primero no".format(a,b) )

np.sqrt(-1)= nan y np.emath.sqrt(-1)=1j No son iguales ya que el segundo maneja complejos y el primero no


C:\Users\ASUS\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


In [69]:
#33. How to get the dates of yesterday, today and tomorrow?
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

In [70]:
#34. How to get all the dates corresponding to the month of July 2016?
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [71]:
#35. How to compute ((A+B)*(-A/2)) in place (without copy)?
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])