In [1]:
import numpy as np

In [38]:
a=np.array([1,2,3])
b=np.array([1.2,4.0,3.0]) 

In [39]:
print(a,"Tipo dato {}".format(a.dtype),"\n")
print(b,"Tipo dato {}".format(b.dtype),"\n") 

[1 2 3] Tipo dato int64 

[1.2 4.  3. ] Tipo dato float64 



In [64]:
m1=np.matrix('1 2; 3 4')
m2=np.matrix([[1, 2], [3, 4]])
print(m1,"\n")
print(m2,"\n")
m3=np.matmul(m1, m2) #Multiplicaciòn 
print(m4)

[[1 2]
 [3 4]] 

[[1 2]
 [3 4]] 

[[ 7 10]
 [15 22]] 

S
[[ 7 10]
 [15 22]]


In [69]:
Azero=np.zeros(5)
print(Azero,"\n")

#Si se quiere tambièn se llena de solo unos
print(np.ones(5),"\n")

Mzero=np.zeros((5,4))
print(Mzero,"\n")

Arange=np.arange(10,21)
print(Arange,"\n")

#Aqui le estoy diciendo que quiero que divida las distancias
Lrange=np.linspace(1,2,5)
print(Lrange)

[0. 0. 0. 0. 0.] 

[1. 1. 1. 1. 1.] 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[10 11 12 13 14 15 16 17 18 19 20] 

[1.   1.25 1.5  1.75 2.  ]


In [52]:
print(np.arange(10000))
#Numpy que dice que cuando mi array supere los 1000 elementos la mostrará de esta forma

[   0    1    2 ... 9997 9998 9999]


In [53]:
np.set_printoptions(threshold=10)
print(np.arange(10))  # [0 1 2 3 4 5 6 7 8 9]
print(np.arange(11))  # [ 0  1  2 ...  8  9 10]
np.set_printoptions(threshold=1000)  # Volver a la normalidad

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2 ...  8  9 10]


In [55]:
a = np.identity(3)  # Matriz de identidad de 3x3
print(a,"\n")
a = np.eye(3, k=1)   # La muevo hacia arriba
print(a,"\n")
a = np.eye(3, k=-1)  # La muevo hacia abajo
print(a,"\n")

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]] 

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]] 



In [58]:
# Linked Memory
a = np.array([1, 2, 3])  # Creo una array
b = a                    # La reasigno a otra variable
a[0] = 50                # Modifico a
print(b)                 # Muestro b
# [50  2  3]
c=np.array([3])
np.shares_memory(a, b) #Comprobar que comparten la misma memoria
np.shares_memory(a, c)

[50  2  3]


False

In [70]:
#Operaciones
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a.sum())
print(a.min())
print(a.max())

55
1
10


In [79]:
import sys
S=range(1000)
print("Resultados lista Python:")
# getsizeof = Return the size of an object in bytes. The object can be any type of object. 
#All built-in objects will return correct results, but this does not have to 
# hold true for third-party extensions as it is implementation specific.
print(sys.getsizeof(1)," * ",len(S)," = ",sys.getsizeof(1)*len(S) ,"\n")
D=np.arange(1000)
print("Resultados lista Numpy:","\n")
print(D.size," * ",D.itemsize," = ",D.size*D.itemsize)

Resultados lista Python:
28  *  1000  =  28000 

Resultados lista Numpy: 

1000  *  8  =  8000


In [11]:
print(np.ones((3,3)),"\n")
x=np.ones((3,3))
print(x[:, [0,1,2,2] ]) 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
x=np.ones((3,3))
y=x[:2,:2]

y[0,0]=13
print(x)

[[13.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [20]:
from numpy.lib.stride_tricks import as_strided
x=np.arange(16)
y=as_strided(x,(7,4),(8,4),(3,2))
print(y)

[[          0  4294967296           1  8589934592]
 [          1  8589934592           2 12884901888]
 [          2 12884901888           3 17179869184]
 [          3 17179869184           4 21474836480]
 [          4 21474836480           5 25769803776]
 [          5 25769803776           6 30064771072]
 [          6 30064771072           7 34359738368]]


In [24]:
n=8
x=np.arange(n)
k=5
y=as_strided(x,(k,n-k+1),(x.itemsize,)*2)
print(y)

[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


In [ ]:
#s=input("Entrada: ")
import numpy as np
n=(input("Digite num con espacio: "))
array=n.split(" ")   
d=np.array(list(map(float, array)) )

print(np.array(np.round(d),dtype=int))

masa=int(input("Digite masa: "))
print(masa*9.8)

In [ ]:

print("Hello")