In [1]:
#Ejercicio 1:  Importar numpy como np y imprimir la versión
#Respuesta:
import numpy as np
print(np.__version__)

1.18.1


In [2]:
#Ejercicio 2: ¿Cómo crear un arreglo 1D? 
#Crear un arreglo de 0 a 0

#Respuesta:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
#Ejercicio 3: ¿Cómo crear un arreglo booleano?
# Crear un arreglo 3x3 llenado de True

#Respuesta:
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [7]:
#Ejercicio 4: ¿Cómo extraer los items que satisface cierta condición de un arreglo 1D?
#Extraer todos los impares de arr
arr = np.arange(10)

#Respuesta:
arr[arr%2==1]

array([1, 3, 5, 7, 9])

In [8]:
#Ejercicio 5: ¿Cómo reemplazar items que satisface una condición con otro valor en el arreglo?
#Reemplazar todos los impares por -1
arr = np.arange(10)

#Respuesta:
arr[arr%2==1]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [12]:
#Ejercicio 6: ¿Cómo reemplazr items que satisface una condición sin afectar el arreglo original?
#Reemplaze todos los impares por -1 sin afectar el arreglo arr
arr = np.arange(10)

#Respuesta:
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [13]:
#Ejercicio 7: ¿Cómo remodelar un arreglo?
#Convierta un arreglo 1D en un arreglo 2D con 2 filas
arr = np.arange(10)

#Respuesta:
arr.reshape(2, -1)  #Enviando -1: numpy automaticamente decide el numero de columnas

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
#Ejercicio 8: ¿Cómo apilar 2 arreglos verticalmente?
#Apile el arreglo a y b verticalmente
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1) 

# Respuestas
# Metódo 1:
np.concatenate([a, b], axis=0)

# Metódo 2:
np.vstack([a, b])

# Metódo 3:
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [15]:
#Ejercicio 9: ¿Cómo apliar 2 arreglos horizontalmente?
#Apile el arreglo a y b horizontalmente
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Respuestas
# Metodo 1:
np.concatenate([a, b], axis=1)

# Metodo 2:
np.hstack([a, b])

# Metodo 3:
np.c_[a, b] 

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [17]:
#Ejercicio 10: ¿Cómo generar secuencias personalizadas en numpy sin hardcoding?
#Cree el siguiente patrón sin hardcoding. Utilice solo funciones numpy y la siguien te matriz de entrada a
a = np.array([1,2,3])

#Respuesta:
np.r_[np.repeat(a, 3), np.tile(a, 3)]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [18]:
#Ejercicio 11: ¿Cómo obtener los items comunes de dos arreglos numpy?
#Obtener los items comunes de a y b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

#Respuesta:
np.intersect1d(a,b)

array([2, 4])

In [19]:
#Ejercicio 12: ¿Cómo eliminar los items de una arreglo que no existen en otro?
#Del arreglo 'a' eliminar todos los elementos presentes en la matriz 'b'
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

#Respuesta:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [20]:
#Ejercicio 13: ¿Cómo obtener las posiciones donde coinciden los elementos de dos matrices?
#Obtenga las posiciones donde los elementos de 'a' y 'b' coinciden
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

#Respueta:
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

In [21]:
#Ejercicio 14: ¿Cómo extraer todos los números entre un rango dado de un arreglo numpy?
#Obtenga todos los artículos entre 5 y 10 de 'a'.
a = np.arange(15)

#Respuestas
# Metódo 1
index = np.where((a >= 5) & (a <= 10))
a[index]

# Metódo 2:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]

# Metódo 3:  
a[(a >= 5) & (a <= 10)]

array([ 5,  6,  7,  8,  9, 10])

In [22]:
#Ejercicio 15: ¿Cómo hacer una función de python que maneje escalares para trabajar en arreglos numpy?
#Convierta la función 'maxx' que funciona en dos escalares, para trabajar en dos matrices.
def maxx(x, y):
    """Obtiene el máximo de dos items"""
    if x >= y:
        return x
    else:
        return y
    
#Respuesta:
pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

In [24]:
#Ejercicio 16: ¿Cómo intercambiar dos columnas en un arreglo numpy 2d?
#Intercambie las columnas 1 y 2 en la matriz arr

arr = np.arange(9).reshape(3,3) 

#Respuesta:
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [27]:
#Ejercicio 17: ¿Cómo intercambiar dos filas en un arreglo numpy 2d?
#Intercambie las filas 1 y 2 en la matriz arr
arr = np.arange(9).reshape(3,3)

#Respuesta:
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [28]:
#Ejercicio 18: ¿Cómo invertir las filas de una arreglo 2D?
#Invierta las filas de una arreglo 2D 'arr'.
arr = np.arange(9).reshape(3,3)

#Respuesta:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [30]:
#Ejercicio 19: ¿Cómo invertir las columnas de una arreglo 2D?
#Invierta las columnas de una arreglo 2D 'arr'.
arr = np.arange(9).reshape(3,3)

#Respuesta:
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [31]:
#Ejercicio 20: ¿Cómo crear una matriz 2D que contenga flotantes aleatorios entre 5 y 10?
#Cree una matriz 2D de forma 5x3 para contener números decimales aleatorios entre 5 y 10

arr = np.arange(9).reshape(3,3)

#Respuestas
# Método 1:
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
#print(rand_arr)

# Método 2:
rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)

[[8.29526015 6.83069239 5.58943836]
 [5.99365526 8.60953031 5.4493788 ]
 [8.83895499 8.63318176 8.98088451]
 [6.21977817 9.8661416  7.15089648]
 [6.78898993 6.56759097 6.12007289]]
[[5.78717282 6.44363481 9.58575083]
 [8.9831279  8.30736536 9.38724571]
 [6.01383075 6.28514678 5.20920288]
 [5.32521561 9.6345436  6.61910457]
 [6.80394941 8.08817932 5.33715044]]


In [37]:
#Ejercicio 21: ¿Cómo imprimir solo 3 lugares decimales en la matriz numpy de python?
#Imprime o muestra solo 3 decimales de la matriz numpy 'rand_arr'
rand_arr = np.random.random((5,3))

#Respuesta:
np.set_printoptions(precision=3)
rand_arr[:4]

array([[0.399, 0.267, 0.086],
       [0.87 , 0.947, 0.574],
       [0.886, 0.773, 0.894],
       [0.997, 0.926, 0.785]])

In [41]:
#Ejercicio 22: ¿Cómo imprimir bonito una matriz numpy suprimiendo la notación científica (como 1e10)?
#Imprime rand_arr de forma bonita suprimiendo la notación científica (como 1e10)

#Resetiar del ejercicio anterior
np.set_printoptions(suppress=False)

# Creando una matriz randon
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

#Respuesta:
np.set_printoptions(suppress=True, precision=6)  # precision is optional
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

In [44]:
#Ejercicio 23: ¿Cómo limitar el número de elementos impresos en la salida de una matriz numpy?
#Limite el número de elementos impresos en python numpy array a a un máximo de 6 elementos.

a = np.arange(15)

#Respuesta:
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [55]:
#Ejercicio 24: ¿Cómo imprimir la matriz numpy completa sin truncar?
#Imprima la matriz numpy completa a sin truncar.
np.set_printoptions(threshold=6)
a = np.arange(15)

#Respuesta:
np.set_printoptions(threshold=1000) #1000 es por defecto threshol 
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])